---
- name: Setup Java Maven Application Build Server
  hosts: all
  become: yes

  tasks:
    - name: Install default Java JDK (Development Kit)
      dnf:
        name: java-devel
        state: present
        update_cache: yes

    - name: Install Maven
      dnf:
        name: maven
        state: present

    - name: Create build directory
      file:
        path: /opt/build
        state: directory
        mode: '0755'

    - name: Verify Installations
      shell: "java -version && mvn -version"
      register: version_output

    - name: Print success message
      debug:
        msg: 
          - "Java and Maven installation completed successfully!"
          - "{{ version_output.stderr_lines }}"